[tool.poetry]
name = "influx-cli"
version = "0.1.0"
description = ""
authors = ["vonum <vonum.mk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
influxdb-client = "^1.38.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
