docker run \
  -p 8086:8086 \
  -e DOCKER_INFLUXDB_INIT_MODE=setup \
  -e DOCKER_INFLUXDB_INIT_USERNAME=test \
  -e DOCKER_INFLUXDB_INIT_PASSWORD=test1234567 \
  -e DOCKER_INFLUXDB_INIT_ORG=test \
  -e DOCKER_INFLUXDB_INIT_BUCKET=test \
  -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=test \
  influxdb:latest
